# Generated by Django 2.2.3 on 2019-08-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
    ]
